[versions]
aws_sdk = "2.41.15"
log4j2 = "2.24.0"
slf4j = "2.0.16"
guava = "33.4.8-jre"
jackson = "2.18.4"

[libraries]
assertj = "org.assertj:assertj-core:3.15.0"
assertj_guava = "org.assertj:assertj-guava:3.4.0"

autovalue_annotations = "com.google.auto.value:auto-value-annotations:1.11.0"
autovalue = "com.google.auto.value:auto-value:1.11.0"

aws_bom = { module = "software.amazon.awssdk:bom", version.ref = "aws_sdk" }
aws_http = { module = "software.amazon.awssdk:apache-client" }
aws_s3 = { module = "software.amazon.awssdk:s3" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

jackson_yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

jsr305 = "com.google.code.findbugs:jsr305:3.0.2"

junit = "junit:junit:4.13.2"

log4j_core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }
log4j_api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2" }
log4j_jpl = { module = "org.apache.logging.log4j:log4j-jpl", version.ref = "log4j2" }
log4j_jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j2" }
log4j_slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j2" }

slf4j_api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j_ext = { module = "org.slf4j:slf4j-ext", version.ref = "slf4j" }

commons_logging = "commons-logging:commons-logging:1.3.4"